# Auto-generated by IDE. All changes by user will be lost!
# Created at 4/22/13 5:41 PM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/main.cpp \
    $$BASEDIR/src/millionSec.cpp

HEADERS +=  \
    $$BASEDIR/src/millionSec.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

